/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-web`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/driver-apply`; params?: Router.UnknownInputParams; } | { pathname: `/driver-list`; params?: Router.UnknownInputParams; } | { pathname: `/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/request-sent`; params?: Router.UnknownInputParams; } | { pathname: `/ride`; params?: Router.UnknownInputParams; } | { pathname: `/tracking`; params?: Router.UnknownInputParams; } | { pathname: `/trip-rating`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/driver/home`; params?: Router.UnknownInputParams; } | { pathname: `/driver/trip`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin-web`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-apply`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-list`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/request-sent`; params?: Router.UnknownOutputParams; } | { pathname: `/ride`; params?: Router.UnknownOutputParams; } | { pathname: `/tracking`; params?: Router.UnknownOutputParams; } | { pathname: `/trip-rating`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/home`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/trip`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin-web${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/driver-apply${`?${string}` | `#${string}` | ''}` | `/driver-list${`?${string}` | `#${string}` | ''}` | `/profile-setup${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/request-sent${`?${string}` | `#${string}` | ''}` | `/ride${`?${string}` | `#${string}` | ''}` | `/tracking${`?${string}` | `#${string}` | ''}` | `/trip-rating${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/driver/home${`?${string}` | `#${string}` | ''}` | `/driver/trip${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-web`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/driver-apply`; params?: Router.UnknownInputParams; } | { pathname: `/driver-list`; params?: Router.UnknownInputParams; } | { pathname: `/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/request-sent`; params?: Router.UnknownInputParams; } | { pathname: `/ride`; params?: Router.UnknownInputParams; } | { pathname: `/tracking`; params?: Router.UnknownInputParams; } | { pathname: `/trip-rating`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/driver/home`; params?: Router.UnknownInputParams; } | { pathname: `/driver/trip`; params?: Router.UnknownInputParams; };
    }
  }
}
